"""
Django settings for Project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1'
).split(',') if host.strip()]

ALLOWED_REGISTRATION_DOMAINS = tuple(
    domain.strip().lower() for domain in os.environ.get(
        'ALLOWED_REGISTRATION_DOMAINS', 'iic.edu.np'
    ).split(',') if domain.strip()
)
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'helpdesk',
    'drf_spectacular',
    'drf_spectacular_sidecar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Strip COOP from /media/ responses so Chrome can render PDFs in iframes.
    'Project.middleware.MediaCoopMiddleware',
]

# Allow same-origin framing so the PDF viewer modal can embed media files
# served from the same origin. Cross-origin framing is still blocked.
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'Project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'auth_login': '10/minute',
        'auth_register': '5/hour',
        'auth_google': '10/minute',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

AUTHENTICATION_BACKENDS = [
    'helpdesk.authentication.EmailOrUsernameBackend',
]

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get(
    'CSRF_TRUSTED_ORIGINS', 'http://localhost:3000'
).split(',') if origin.strip()]


# ── Email configuration (Django 6.1 MAILERS format) ───────────────────────
#
# Django 6.1 replaced the legacy EMAIL_BACKEND / EMAIL_HOST / EMAIL_PORT /
# EMAIL_HOST_USER / EMAIL_HOST_PASSWORD / EMAIL_USE_TLS settings with the
# unified MAILERS dict.  Setting both simultaneously raises
# ImproperlyConfigured, so ALL email configuration must live here.
#
# Environment variables read (all optional — safe defaults shown):
#
#   MAILER_BACKEND        Backend path
#                         default: django.core.mail.backends.console.EmailBackend
#                         production: django.core.mail.backends.smtp.EmailBackend
#
#   MAILER_HOST           SMTP hostname       (default: localhost)
#   MAILER_PORT           SMTP port           (default: 587)
#   MAILER_USE_TLS        "true"/"false"      (default: true)
#   MAILER_USE_SSL        "true"/"false"      (default: false)
#   MAILER_USERNAME       SMTP login          (default: "")
#   MAILER_PASSWORD       SMTP password       (default: "")  — keep secret
#   MAILER_TIMEOUT        Connection timeout  (default: 30)
#
# Note: use MAILER_* prefixes (not EMAIL_*) to avoid the deprecated settings
# namespace that Django 6.1 now forbids when MAILERS is defined.

def _bool(value: str, default: bool) -> bool:
    if not value:
        return default
    return value.strip().lower() in ('1', 'true', 'yes')


_mailer_backend  = os.environ.get('MAILER_BACKEND',  'django.core.mail.backends.console.EmailBackend')
_mailer_host     = os.environ.get('MAILER_HOST',     'localhost')
_mailer_port     = int(os.environ.get('MAILER_PORT', '587'))
_mailer_use_tls  = _bool(os.environ.get('MAILER_USE_TLS',  ''), True)
_mailer_use_ssl  = _bool(os.environ.get('MAILER_USE_SSL',  ''), False)
_mailer_username = os.environ.get('MAILER_USERNAME', '')
_mailer_password = os.environ.get('MAILER_PASSWORD', '')
_mailer_timeout  = int(os.environ.get('MAILER_TIMEOUT', '30'))

# Build SMTP OPTIONS dict — only include non-empty values so the console
# backend (which ignores OPTIONS entirely) is not given irrelevant kwargs.
_smtp_options: dict = {
    'host':     _mailer_host,
    'port':     _mailer_port,
    'use_tls':  _mailer_use_tls,
    'use_ssl':  _mailer_use_ssl,
    'timeout':  _mailer_timeout,
}
if _mailer_username:
    _smtp_options['username'] = _mailer_username
if _mailer_password:
    _smtp_options['password'] = _mailer_password  # value read from env, not hardcoded

MAILERS = {
    'default': {
        'BACKEND': _mailer_backend,
        'OPTIONS': _smtp_options,
    },
}

# ── Verification-specific settings (not email transport — safe to set here) ─
VERIFICATION_FROM_EMAIL         = os.environ.get('VERIFICATION_FROM_EMAIL', 'noreply@iic.edu.np')
VERIFICATION_TOKEN_EXPIRY_HOURS = int(os.environ.get('VERIFICATION_TOKEN_EXPIRY_HOURS', '24'))
EMAIL_VERIFICATION_ENABLED      = _bool(os.environ.get('EMAIL_VERIFICATION_ENABLED', ''), True)

# ── Default intern category scope slugs ─────────────────────────────────────
# Used as a fallback when the InternCategoryScope table is empty (e.g., before
# the seed migration has run).
HELPDESK_INTERN_SCOPE_SLUGS = [
    'device-support',
    'wifi-issue',
    'general-support',
]

HELPDESK_URL = os.environ.get('HELPDESK_URL', 'http://localhost:3000')

# Optional: Customize API title, version, and Swagger behavior
SPECTACULAR_SETTINGS = {
    'TITLE': 'IIC-IT Help Desk Application',
    'DESCRIPTION': 'API documentation generated automatically',
    'VERSION': '0.0.1',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}
