from django.urls import path, re_path

from .views import (
    CsrfView,
    CurrentUserView,
    AdminGuideDetail,
    AdminGuideListCreate,
    AdminServiceCategoryDetail,
    AdminServiceCategoryList,
    AdminServiceCategoryReorder,
    AdminSoftwareDetail,
    AdminSoftwareListCreate,
    AdminSummaryView,
    AdminUserDetail,
    AdminUserList,
    GoogleLoginView,
    LoginView,
    LogoutView,
    RegisterView,
    PublicGuideList,
    PublicSoftwareList,
    ServiceCategoryList,
    TicketAssignView,
    TicketDetail,
    TicketListCreate,
    UserRoleDetail,
    UserRoleListCreate,
    health,
)

urlpatterns = [
    path('health/', health, name='health'),
    re_path(r'^auth/csrf/?$', CsrfView.as_view(), name='auth-csrf'),
    re_path(r'^auth/me/?$', CurrentUserView.as_view(), name='auth-me'),
    re_path(r'^auth/register/?$', RegisterView.as_view(), name='auth-register'),
    re_path(r'^auth/login/?$', LoginView.as_view(), name='auth-login'),
    re_path(r'^auth/google/?$', GoogleLoginView.as_view(), name='auth-google'),
    re_path(r'^auth/logout/?$', LogoutView.as_view(), name='auth-logout'),
    path('services/', ServiceCategoryList.as_view(), name='service-list'),
    path('tickets/', TicketListCreate.as_view(), name='ticket-list-create'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/?$', TicketDetail.as_view(), name='ticket-detail'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/assign/?$', TicketAssignView.as_view(), name='ticket-assign'),
    re_path(r'^guides/?$', PublicGuideList.as_view(), name='public-guide-list'),
    re_path(r'^software/?$', PublicSoftwareList.as_view(), name='public-software-list'),
    re_path(r'^admin/summary/?$', AdminSummaryView.as_view(), name='admin-summary'),
    re_path(r'^admin/services/?$', AdminServiceCategoryList.as_view(), name='admin-service-list'),
    re_path(r'^admin/services/reorder/?$', AdminServiceCategoryReorder.as_view(), name='admin-service-reorder'),
    re_path(r'^admin/services/(?P<pk>[0-9]+)/?$', AdminServiceCategoryDetail.as_view(), name='admin-service-detail'),
    re_path(r'^admin/guides/?$', AdminGuideListCreate.as_view(), name='admin-guide-list'),
    re_path(r'^admin/guides/(?P<pk>[0-9]+)/?$', AdminGuideDetail.as_view(), name='admin-guide-detail'),
    re_path(r'^admin/software/?$', AdminSoftwareListCreate.as_view(), name='admin-software-list'),
    re_path(r'^admin/software/(?P<pk>[0-9]+)/?$', AdminSoftwareDetail.as_view(), name='admin-software-detail'),
    re_path(r'^admin/users/?$', AdminUserList.as_view(), name='admin-user-list'),
    re_path(r'^admin/users/(?P<pk>[0-9]+)/?$', AdminUserDetail.as_view(), name='admin-user-detail'),
    re_path(r'^admin/users/(?P<pk>[0-9]+)/roles/?$', UserRoleListCreate.as_view(), name='admin-user-roles'),
    re_path(r'^admin/users/(?P<pk>[0-9]+)/roles/(?P<role>[a-z_]+)/?$', UserRoleDetail.as_view(), name='admin-user-role-detail'),
]
