from django.urls import path, re_path

from .views import (
    SuspendUserView,
    RateLimitRuleListCreate,
    RateLimitRuleDetail,
    RateLimitViolationListView,
    RateLimitViolationDetail,
    RateLimitViolationBulkResolveView,
    RateLimitStatsView,
    RateLimitSeedView,
    DeleteUserView,
    ActiveAnnouncementView,
    AdminAnnouncementDetail,
    AdminAnnouncementListCreate,
    AccountRecoveryCodeView,
    RecoveryActionView,
    SetSuperuserView,
    CsrfView,
    CurrentUserView,
    AdminGuideDetail,
    AdminGuideListCreate,
    AdminServiceCategoryDetail,
    AdminServiceCategoryList,
    AdminServiceCategoryReorder,
    AdminSoftwareDetail,
    AdminSoftwareListCreate,
    AdminSummaryView,
    AdminDashboardStreamView,
    AdminUserDetail,
    AdminUserList,
    EmailTemplateDetail,
    EmailTemplateListCreate,
    GoogleLoginView,
    InternScopeDetailView,
    InternScopeListView,
    LoginView,
    LogoutView,
    NotificationChannelDetail,
    NotificationChannelListCreate,
    NotificationChannelTestView,
    NotificationLogListView,
    NotificationRuleDetail,
    NotificationRuleListCreate,
    RegisterView,
    PublicGuideList,
    PublicSoftwareList,
    RoleConfigDetailView,
    RoleConfigListView,
    ServiceCategoryList,
    TicketAssignView,
    TicketDetail,
    TicketFormSettingsView,
    TicketListCreate,
    TicketExportView,
    TicketStreamView,
    TicketMessageListCreate,
    TicketAttachmentListView,
    TicketEventListView,
    AssignableStaffView,
    TicketStatusView,
    UserRoleDetail,
    UserRoleListCreate,
    health,
    VerifyEmailView,
    ResendVerificationView,
    ForgotPasswordView,
    ResetPasswordView,
    UserProfileView,
    ChangePasswordView,
    SiteSettingsView,
    PublicServiceStatusView,
    AdminServiceStatusListView,
    AdminServiceStatusDetailView,
    TicketFeedbackView,
    AdminFeedbackListView,
    SoftwareDownloadView,
    InitChunkedUploadView,
    UploadChunkView,
    FinalizeChunkedUploadView,
)
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
    SpectacularRedocView,
)

urlpatterns = [
    path('health/', health, name='health'),
    re_path(r'^auth/csrf/?$',      CsrfView.as_view(),       name='auth-csrf'),
    re_path(r'^auth/me/?$',        CurrentUserView.as_view(), name='auth-me'),
    re_path(r'^auth/register/?$',  RegisterView.as_view(),    name='auth-register'),
    re_path(r'^auth/login/?$',     LoginView.as_view(),       name='auth-login'),
    re_path(r'^auth/google/?$',    GoogleLoginView.as_view(), name='auth-google'),
    re_path(r'^auth/logout/?$',    LogoutView.as_view(),      name='auth-logout'),
    re_path(r'^auth/verify-email/?$',     VerifyEmailView.as_view(),      name='auth-verify-email'),
    re_path(r'^auth/resend-verification/?$', ResendVerificationView.as_view(), name='auth-resend-verification'),
    re_path(r'^auth/forgot-password/?$',     ForgotPasswordView.as_view(),  name='auth-forgot-password'),
    re_path(r'^auth/reset-password/?$',      ResetPasswordView.as_view(),   name='auth-reset-password'),
    re_path(r'^auth/profile/?$',             UserProfileView.as_view(),     name='auth-profile'),
    re_path(r'^auth/change-password/?$',     ChangePasswordView.as_view(),  name='auth-change-password'),

    path('services/', ServiceCategoryList.as_view(), name='service-list'),

    path('tickets/', TicketListCreate.as_view(), name='ticket-list-create'),
    re_path(r'^tickets/export/?$', TicketExportView.as_view(), name='ticket-export'),
    re_path(r'^tickets/assignable-staff/?$',                          AssignableStaffView.as_view(),     name='assignable-staff'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/stream/?$',                 TicketStreamView.as_view(),        name='ticket-stream'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/status/?$',                 TicketStatusView.as_view(),        name='ticket-status'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/messages/?$',               TicketMessageListCreate.as_view(), name='ticket-messages'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/attachments/?$',            TicketAttachmentListView.as_view(),name='ticket-attachments'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/events/?$',                 TicketEventListView.as_view(),     name='ticket-events'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/recovery-code/?$',          AccountRecoveryCodeView.as_view(), name='ticket-recovery-code'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/recovery-action/?$',        RecoveryActionView.as_view(),      name='ticket-recovery-action'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/?$',                        TicketDetail.as_view(),            name='ticket-detail'),
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/assign/?$',                 TicketAssignView.as_view(),        name='ticket-assign'),

    re_path(r'^guides/?$',   PublicGuideList.as_view(),   name='public-guide-list'),
    re_path(r'^software/?$', PublicSoftwareList.as_view(), name='public-software-list'),
    re_path(r'^software/(?P<slug>[a-z0-9-]+)/download/?$', SoftwareDownloadView.as_view(), name='software-download'),

    # ── Admin ──────────────────────────────────────────────────────────────
    re_path(r'^admin/summary/?$',                AdminSummaryView.as_view(),          name='admin-summary'),
    re_path(r'^admin/summary/stream/?$',         AdminDashboardStreamView.as_view(),  name='admin-summary-stream'),
    re_path(r'^admin/services/?$',               AdminServiceCategoryList.as_view(),  name='admin-service-list'),
    re_path(r'^admin/services/reorder/?$',       AdminServiceCategoryReorder.as_view(),name='admin-service-reorder'),
    re_path(r'^admin/services/(?P<pk>[0-9]+)/?$',AdminServiceCategoryDetail.as_view(),name='admin-service-detail'),
    re_path(r'^admin/guides/?$',                 AdminGuideListCreate.as_view(),      name='admin-guide-list'),
    re_path(r'^admin/guides/(?P<pk>[0-9]+)/?$',  AdminGuideDetail.as_view(),          name='admin-guide-detail'),
    re_path(r'^admin/software/?$',               AdminSoftwareListCreate.as_view(),   name='admin-software-list'),
    re_path(r'^admin/software/(?P<pk>[0-9]+)/?$',AdminSoftwareDetail.as_view(),       name='admin-software-detail'),
    re_path(r'^admin/users/?$',                  AdminUserList.as_view(),             name='admin-user-list'),
    re_path(r'^admin/users/(?P<pk>[0-9]+)/?$',   AdminUserDetail.as_view(),           name='admin-user-detail'),
    re_path(r'^admin/users/(?P<pk>[0-9]+)/roles/?$',                    UserRoleListCreate.as_view(), name='admin-user-roles'),
    re_path(r'^admin/users/(?P<pk>[0-9]+)/roles/(?P<role>[a-z_]+)/?$', UserRoleDetail.as_view(),     name='admin-user-role-detail'),
    re_path(r'^admin/users/(?P<pk>[0-9]+)/suspend/?$',                  SuspendUserView.as_view(),    name='admin-user-suspend'),
    re_path(r'^admin/users/(?P<pk>[0-9]+)/delete/?$',                   DeleteUserView.as_view(),     name='admin-user-delete'),
    re_path(r'^admin/users/(?P<pk>[0-9]+)/set-superuser/?$',            SetSuperuserView.as_view(),   name='admin-user-set-superuser'),

    # Notification channels — test must come before {pk} pattern
    re_path(r'^admin/notifications/channels/?$',               NotificationChannelListCreate.as_view(), name='notification-channel-list'),
    re_path(r'^admin/notifications/channels/test/?$',          NotificationChannelTestView.as_view(),   name='notification-channel-test'),
    re_path(r'^admin/notifications/channels/(?P<pk>[0-9]+)/?$',NotificationChannelDetail.as_view(),    name='notification-channel-detail'),
    re_path(r'^admin/notifications/templates/?$',              EmailTemplateListCreate.as_view(),       name='notification-template-list'),
    re_path(r'^admin/notifications/templates/(?P<pk>[0-9]+)/?$',EmailTemplateDetail.as_view(),         name='notification-template-detail'),
    re_path(r'^admin/notifications/logs/?$',                   NotificationLogListView.as_view(),       name='notification-log-list'),
    re_path(r'^admin/notifications/rules/?$',                  NotificationRuleListCreate.as_view(),    name='notification-rule-list'),
    re_path(r'^admin/notifications/rules/(?P<pk>[0-9]+)/?$',   NotificationRuleDetail.as_view(),       name='notification-rule-detail'),

    # Settings
    re_path(r'^admin/settings/ticket-form/?$',                    TicketFormSettingsView.as_view(),  name='settings-ticket-form'),
    re_path(r'^settings/site/?$',                                 SiteSettingsView.as_view(),        name='settings-site-public'),
    re_path(r'^admin/settings/site/?$',                           SiteSettingsView.as_view(),        name='settings-site-admin'),
    re_path(r'^admin/settings/roles/?$',                          RoleConfigListView.as_view(),      name='settings-roles'),
    re_path(r'^admin/settings/roles/(?P<role>[a-z_]+)/?$',        RoleConfigDetailView.as_view(),    name='settings-role-detail'),
    re_path(r'^admin/settings/intern-scope/?$',                   InternScopeListView.as_view(),     name='settings-intern-scope'),
    re_path(r'^admin/settings/intern-scope/(?P<slug>[a-z0-9-]+)/?$', InternScopeDetailView.as_view(), name='settings-intern-scope-detail'),

    # Rate limiting
    re_path(r'^admin/rate-limits/stats/?$',                          RateLimitStatsView.as_view(),             name='rate-limit-stats'),
    re_path(r'^admin/rate-limits/seed/?$',                           RateLimitSeedView.as_view(),              name='rate-limit-seed'),
    re_path(r'^admin/rate-limits/rules/?$',                          RateLimitRuleListCreate.as_view(),        name='rate-limit-rule-list'),
    re_path(r'^admin/rate-limits/rules/(?P<pk>[0-9]+)/?$',           RateLimitRuleDetail.as_view(),            name='rate-limit-rule-detail'),
    re_path(r'^admin/rate-limits/violations/?$',                     RateLimitViolationListView.as_view(),     name='rate-limit-violation-list'),
    re_path(r'^admin/rate-limits/violations/resolve-all/?$',         RateLimitViolationBulkResolveView.as_view(), name='rate-limit-resolve-all'),
    re_path(r'^admin/rate-limits/violations/(?P<pk>[0-9]+)/?$',      RateLimitViolationDetail.as_view(),       name='rate-limit-violation-detail'),

    # Announcements
    re_path(r'^announcement/?$',                          ActiveAnnouncementView.as_view(),      name='announcement-active'),
    re_path(r'^admin/announcements/?$',                   AdminAnnouncementListCreate.as_view(), name='admin-announcement-list'),
    re_path(r'^admin/announcements/(?P<pk>[0-9]+)/?$',    AdminAnnouncementDetail.as_view(),     name='admin-announcement-detail'),

    # Service status board
    re_path(r'^status/?$',                                        PublicServiceStatusView.as_view(),        name='public-service-status'),
    re_path(r'^admin/status/?$',                                  AdminServiceStatusListView.as_view(),     name='admin-service-status-list'),
    re_path(r'^admin/status/(?P<category_id>[0-9]+)/?$',          AdminServiceStatusDetailView.as_view(),   name='admin-service-status-detail'),

    # Ticket feedback
    re_path(r'^tickets/(?P<pk>[0-9a-f-]+)/feedback/?$',           TicketFeedbackView.as_view(),             name='ticket-feedback'),
    re_path(r'^admin/feedback/?$',                                 AdminFeedbackListView.as_view(),          name='admin-feedback-list'),

    # Chunked file uploads (bypass Cloudflare 100 MB body limit)
    re_path(r'^upload/init/?$',
            InitChunkedUploadView.as_view(),   name='upload-init'),
    re_path(r'^upload/(?P<upload_id>[0-9a-f-]+)/chunk/(?P<index>[0-9]+)/?$',
            UploadChunkView.as_view(),         name='upload-chunk'),
    re_path(r'^upload/(?P<upload_id>[0-9a-f-]+)/finalize/?$',
            FinalizeChunkedUploadView.as_view(), name='upload-finalize'),

    # Swagger ui for testing
    # 1. Downloads the raw OpenAPI 3 schema YAML/JSON
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),

    # 2. Interactive Swagger UI
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),

    # 3. Optional: Redoc UI (alternative interactive viewer)
    path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]
