# Generated by Django 6.1.1 on 2026-09-11 02:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=240)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('student', 'Students'), ('staff', 'Faculty and staff'), ('all', 'Students and staff')], default='all', max_length=20)),
                ('icon', models.CharField(default='life-buoy', max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('waiting_requester', 'Waiting for requester'), ('waiting_approval', 'Waiting for approval'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='submitted', max_length=24)),
                ('priority', models.CharField(choices=[('p1', 'Critical'), ('p2', 'High'), ('p3', 'Normal'), ('p4', 'Low')], default='p3', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='helpdesk.servicecategory')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
