# Generated by Django 5.2.17 on 2026-09-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_guidearticle_softwareresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidearticle',
            name='content',
        ),
        migrations.AddField(
            model_name='guidearticle',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='guides/%Y/%m/'),
        ),
    ]
