# Generated by Django 6.1.1 on 2026-09-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_seed_role_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='form_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticket',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
