# Generated by Django 5.2.17 on 2026-09-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_seed_service_schemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_reason',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
