# Generated by Django 5.2.17 on 2026-09-14 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_add_ticket_status_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ticket_submitted', 'Ticket Submitted'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_assigned', 'Ticket Assigned'), ('status_changed', 'Status Changed'), ('account_recovery', 'Account Recovery')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('subject_template', models.CharField(max_length=500)),
                ('body_html_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('event_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('discord', 'Discord'), ('google_workspace', 'Google Workspace'), ('teams', 'Microsoft Teams'), ('slack', 'Slack'), ('email_smtp', 'Email (SMTP)'), ('email_mailgun', 'Email (Mailgun)')], max_length=20)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='helpdesk.notificationchannel')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='helpdesk.ticket')),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
    ]
