# Generated by Django 5.2.17 on 2026-09-14 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_seed_notification_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ticket_submitted', 'Ticket Submitted'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_assigned', 'Ticket Assigned'), ('status_changed', 'Status Changed'), ('account_recovery', 'Account Recovery')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('recipient_type', models.CharField(choices=[('requester', 'Ticket requester'), ('assignee', 'Assigned staff member'), ('all_staff', 'All active staff via email'), ('custom', 'Custom email list')], default='requester', max_length=20)),
                ('custom_emails', models.TextField(blank=True, default='', help_text='Comma-separated list of email addresses (only used when recipient_type=custom).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='helpdesk.notificationchannel')),
            ],
            options={
                'ordering': ('event_type', 'channel__name'),
                'unique_together': {('event_type', 'channel')},
            },
        ),
    ]
