# Generated by Django 5.2.17 on 2026-09-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_ticket_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('visitor', 'Visitor'), ('student', 'Student'), ('faculty_staff', 'Faculty and Staff'), ('it_agent', 'IT Agent'), ('it_noc_intern', 'IT NOC Intern'), ('service_lead', 'Service Lead'), ('designated_approver', 'Designated Approver'), ('content_editor', 'Content Editor'), ('administrator', 'Administrator')], max_length=20, unique=True)),
                ('is_grantable', models.BooleanField(default=True, help_text='If False, this role cannot be assigned to new users via the admin panel.')),
                ('description', models.CharField(blank=True, default='', help_text='Short description shown in the roles admin page.', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('role',),
            },
        ),
        migrations.CreateModel(
            name='TicketFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_visible', models.BooleanField(default=True)),
                ('subject_required', models.BooleanField(default=True)),
                ('subject_min_len', models.PositiveSmallIntegerField(default=5)),
                ('subject_max_len', models.PositiveSmallIntegerField(default=150)),
                ('description_visible', models.BooleanField(default=True)),
                ('description_required', models.BooleanField(default=True)),
                ('description_min_len', models.PositiveSmallIntegerField(default=20)),
                ('description_max_len', models.PositiveSmallIntegerField(default=5000)),
                ('impact_visible', models.BooleanField(default=True)),
                ('impact_required', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket form settings',
                'verbose_name_plural': 'Ticket form settings',
            },
        ),
    ]
