# Generated by Django 5.2.17 on 2026-09-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0015_admin_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleconfig',
            name='can_export',
            field=models.BooleanField(default=False, help_text='If True, users with this role may download ticket export reports.'),
        ),
    ]
