# Generated by Django 5.2.17 on 2026-09-21 09:44

import helpdesk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_roleconfig_can_export'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.SlugField(help_text='Short unique slug identifying this campaign, e.g. "orientation-2026". Changing this causes the modal to re-show for users who already dismissed it.', max_length=80, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Internal label — not shown publicly.', max_length=160)),
                ('image', models.ImageField(help_text='Banner/flyer image (JPEG, PNG, WebP). Recommended: 800 × 600 px.', upload_to=helpdesk.models.announcement_image_path)),
                ('alt_text', models.CharField(help_text='Descriptive alt text for screen readers.', max_length=300)),
                ('link_url', models.URLField(blank=True, default='', help_text='Optional URL the banner links to (leave blank for image-only).')),
                ('is_active', models.BooleanField(default=False, help_text='Only active announcements are served to the public home page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ('-updated_at',),
            },
        ),
    ]
