# Generated by Django 5.2.17 on 2026-09-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0017_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks the account as suspended. The user will see a notice at login.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', help_text='Reason shown to the user when their account is suspended.', max_length=500),
        ),
    ]
