# Generated by Django 5.2.17 on 2026-09-23 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_suspension_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text='Short scope key that the throttle class looks up.', max_length=60, unique=True)),
                ('label', models.CharField(blank=True, help_text='Human-readable label shown in the admin UI.', max_length=160)),
                ('description', models.TextField(blank=True, help_text='Explains what this rule protects.')),
                ('limit', models.PositiveIntegerField(help_text='Maximum number of requests allowed in the window.')),
                ('window', models.CharField(choices=[('second', 'Per second'), ('minute', 'Per minute'), ('hour', 'Per hour'), ('day', 'Per day')], default='minute', max_length=10)),
                ('violation_action', models.CharField(choices=[('block', 'Block the request (429)'), ('warn', 'Allow but log the violation'), ('suspend', 'Suspend the account automatically')], default='block', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rules are ignored by the throttle engine.')),
                ('violation_threshold', models.PositiveSmallIntegerField(default=0, help_text='Number of additional requests above the limit before the violation action fires. 0 = fire immediately on first excess request.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate limit rule',
                'verbose_name_plural': 'Rate limit rules',
                'ordering': ('scope',),
            },
        ),
        migrations.CreateModel(
            name='RateLimitViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, help_text='IP address or "user:<pk>".', max_length=100)),
                ('request_count', models.PositiveIntegerField(default=1, help_text='Total requests seen in the window when this violation was logged.')),
                ('action_taken', models.CharField(choices=[('blocked', 'Request blocked (429)'), ('warned', 'Allowed but logged'), ('suspended', 'Account suspended')], max_length=12)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Admins can mark a violation resolved after reviewing it.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes on this violation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='helpdesk.ratelimitrule')),
                ('user', models.ForeignKey(blank=True, help_text='Populated when the request is authenticated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_limit_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rate limit violation',
                'verbose_name_plural': 'Rate limit violations',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['identifier', 'rule'], name='rl_violation_id_rule_idx'), models.Index(fields=['created_at'], name='rl_violation_created_idx'), models.Index(fields=['is_resolved'], name='rl_violation_resolved_idx')],
            },
        ),
    ]
