# Generated by Django 5.2.17 on 2026-09-24 03:35

# ---------------------------------------------------------------------------
# MIGRATION POLICY DECISION — email_verified for existing accounts
# ---------------------------------------------------------------------------
# This migration adds email_verified / email_verified_at to UserProfile and
# creates the EmailVerificationToken model.
#
# Policy for pre-existing users
# ──────────────────────────────
# Users whose accounts existed *before* this migration are considered to have
# a verified email address because:
#   1. Domain restriction (@iic.edu.np) was already enforced at registration.
#   2. Admin-created accounts were provisioned by a trusted administrator.
#   3. Google OAuth accounts already proved email ownership via Google.
#   4. Forcing re-verification would lock out all legitimate existing users.
#
# Therefore the data migration below marks every UserProfile row whose
# User.is_active=True as email_verified=True at the migration timestamp.
# Suspended accounts (is_active=False, profile.is_suspended=True) are left as
# email_verified=False — they are locked out for a different reason and should
# not regain access automatically.
#
# Accounts with is_active=False and is_suspended=False (generic inactive)
# are left as email_verified=False to be consistent — an admin set them
# inactive for a reason.
# ---------------------------------------------------------------------------

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def mark_existing_users_verified(apps, schema_editor):
    """
    Mark all UserProfile rows belonging to active users as email_verified=True.
    This runs once during the migration to preserve access for pre-existing users.
    """
    UserProfile = apps.get_model('helpdesk', 'UserProfile')
    now = timezone.now()
    updated = UserProfile.objects.filter(user__is_active=True).update(
        email_verified=True,
        email_verified_at=now,
    )
    print(f'\n  Marked {updated} existing active user profile(s) as email_verified=True.')


def reverse_mark(apps, schema_editor):
    """Reverse: clear the verified flag (used when reversing the migration)."""
    UserProfile = apps.get_model('helpdesk', 'UserProfile')
    UserProfile.objects.all().update(email_verified=False, email_verified_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_rate_limiting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(
                db_index=True, default=False,
                help_text='True once the user has clicked their verification link.',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='Timestamp when email was first verified.',
            ),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(
                    help_text='SHA-256 hex digest of the raw token. Raw token is never stored.',
                    max_length=64, unique=True,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='verification_tokens',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Email verification token',
                'verbose_name_plural': 'Email verification tokens',
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(fields=['user', 'verified_at'], name='evtoken_user_verified_idx'),
                ],
            },
        ),
        # Data migration: preserve access for pre-existing verified users
        migrations.RunPython(mark_existing_users_verified, reverse_code=reverse_mark),
    ]
