# Generated by Django 5.2.17 on 2026-09-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0020_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='When active, this database configuration overrides .env settings. Deactivate to fall back to .env.')),
                ('backend', models.CharField(choices=[('django.core.mail.backends.console.EmailBackend', 'Console (dev/testing)'), ('django.core.mail.backends.smtp.EmailBackend', 'SMTP'), ('django.core.mail.backends.dummy.EmailBackend', 'Dummy (discard all)'), ('django.core.mail.backends.filebased.EmailBackend', 'File-based'), ('django.core.mail.backends.locmem.EmailBackend', 'In-memory (testing)')], default='django.core.mail.backends.console.EmailBackend', help_text='Email backend to use. Only SMTP requires the host/credentials below.', max_length=100)),
                ('host', models.CharField(blank=True, default='localhost', help_text='SMTP server hostname. Required for SMTP backend.', max_length=253)),
                ('port', models.PositiveIntegerField(default=587, help_text='SMTP port (25 plain, 465 SSL, 587 STARTTLS).')),
                ('use_tls', models.BooleanField(default=True, help_text='Use STARTTLS. Mutually exclusive with use_ssl.')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use implicit SSL/TLS. Mutually exclusive with use_tls.')),
                ('username', models.CharField(blank=True, default='', help_text='SMTP login username (leave blank if not required).', max_length=254)),
                ('password', models.CharField(blank=True, default='', help_text='SMTP password / app password. Masked in the admin interface.', max_length=500)),
                ('timeout', models.PositiveSmallIntegerField(default=30, help_text='SMTP connection timeout in seconds.')),
                ('from_email', models.EmailField(default='noreply@iic.edu.np', help_text='The "From:" address on all outgoing emails.', max_length=254)),
                ('reply_to', models.EmailField(blank=True, default='', help_text='Optional "Reply-To:" address.', max_length=254)),
                ('verification_enabled', models.BooleanField(default=True, help_text='Enable email verification for new registrations.')),
                ('verification_token_expiry_hours', models.PositiveSmallIntegerField(default=24, help_text='Hours before a verification link expires.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email configuration',
                'verbose_name_plural': 'Email configuration',
            },
        ),
    ]
