# Generated by Django 6.1.1 on 2026-09-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0022_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='Google profile picture URL (empty for password-registered users).', max_length=500),
        ),
    ]
