# Generated by Django 6.1.1 on 2026-09-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0023_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event_type',
            field=models.CharField(choices=[('ticket_submitted', 'Ticket Submitted'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_assigned', 'Ticket Assigned'), ('status_changed', 'Status Changed'), ('account_recovery', 'Account Recovery — Send Credentials'), ('recovery_unable_to_verify', 'Account Recovery — Unable to Verify')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('ticket_submitted', 'Ticket Submitted'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_assigned', 'Ticket Assigned'), ('status_changed', 'Status Changed'), ('account_recovery', 'Account Recovery — Send Credentials'), ('recovery_unable_to_verify', 'Account Recovery — Unable to Verify')], max_length=30),
        ),
    ]
