# Generated by Django 6.1.1 on 2026-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0024_recovery_unable_to_verify_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
