# Generated by Django 6.1.1 on 2026-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0025_ticket_description_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
