# Generated by Django 6.1.1 on 2026-09-30 09:07

import django.db.models.deletion
import helpdesk.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0026_ticket_subject_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('public', 'Visitors (unauthenticated)'), ('student', 'Students'), ('staff', 'Faculty & staff')], default='all', help_text='Which users should see this announcement.', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Optional announcement body text or short HTML shown in the modal.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Administrator responsible for this announcement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High'), (3, 'Urgent')], default=1, help_text='Higher priority announcements are shown first when multiple are active.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, help_text='Optional: announcement is hidden after this UTC datetime.', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='Optional: announcement becomes visible after this UTC datetime.', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='alt_text',
            field=models.CharField(blank=True, default='', help_text='Descriptive alt text for screen readers.', max_length=300),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner/flyer image (JPEG, PNG, WebP). Recommended: 800 × 600 px.', upload_to=helpdesk.models.announcement_image_path),
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Ticket created'), ('status_changed', 'Status changed'), ('priority_changed', 'Priority changed'), ('assigned', 'Assigned / reassigned'), ('stage_changed', 'Stage changed'), ('subject_changed', 'Subject edited'), ('team_changed', 'Team changed')], max_length=20)),
                ('old_value', models.CharField(blank=True, default='', help_text='Value before the change (human-readable label, not a raw key).', max_length=200)),
                ('new_value', models.CharField(blank=True, default='', help_text='Value after the change.', max_length=200)),
                ('note', models.CharField(blank=True, default='', help_text='Optional context note (e.g. status reason).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the change. Null for system-generated events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_events', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='helpdesk.ticket')),
            ],
            options={
                'verbose_name': 'Ticket event',
                'verbose_name_plural': 'Ticket events',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='ticket_event_ticket_time_idx'), models.Index(fields=['action'], name='ticket_event_action_idx')],
            },
        ),
    ]
