# Generated by Django 6.1.1 on 2026-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0027_announcement_fields_and_ticket_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.EmailField(default='support@iic.edu.np', help_text='Primary support email shown on the contact page and in emails.', max_length=254)),
                ('office_location', models.CharField(default='IT & NOC Department, Itahari International College, ING, Itahari, Sunsari, Nepal', help_text='Full office address shown on the contact page.', max_length=300)),
                ('office_phone', models.CharField(blank=True, default='', help_text='Optional office phone number.', max_length=60)),
                ('office_hours', models.JSONField(blank=True, default=list, help_text='Office hours as a JSON array of {"day": "...", "hours": "..."} objects. Use "Closed" for hours to mark a closed day. Leave empty to use the frontend defaults.')),
                ('walk_in_note', models.TextField(blank=True, default='', help_text='Walk-in support note shown on the contact page.')),
                ('accessibility_note', models.TextField(blank=True, default='', help_text='Accessibility support note shown on the contact page.')),
                ('account_recovery_note', models.TextField(blank=True, default='', help_text='Account recovery walk-in note shown on the contact page.')),
                ('institution_name', models.CharField(default='Itahari International College', help_text='Full institution name used in emails and the footer.', max_length=160)),
                ('department_name', models.CharField(default='IT & NOC Department', help_text='Department name used in emails and the footer.', max_length=160)),
                ('helpdesk_tagline', models.CharField(blank=True, default='Your first point of contact for IT support, account help, and self-service resources at IIC.', help_text='Short tagline shown in the site footer.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
