# Generated by Django 6.1.1 on 2026-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0028_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='recovery_credentials_destination',
            field=models.CharField(choices=[('college', 'College email (requester account email)'), ('alternative', 'Alternative contact email (from ticket form)')], default='college', help_text='Where to send account recovery credentials. "College email" sends to the requester\'s @iic.edu.np address. "Alternative contact" sends to the personal email they provided on the form.', max_length=15),
        ),
    ]
