# Generated by Django 6.1.1 on 2026-10-06 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0029_site_settings_recovery_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded performance'), ('outage', 'Service outage'), ('maintenance', 'Under maintenance')], default='operational', max_length=16)),
                ('message', models.CharField(blank=True, default='', help_text='Optional short message shown on the status page (e.g. "Scheduled downtime until 14:00").', max_length=500)),
                ('incident_started_at', models.DateTimeField(blank=True, help_text='When this incident/maintenance window began.', null=True)),
                ('estimated_resolution', models.DateTimeField(blank=True, help_text='Estimated time the service will be restored.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(help_text='The service category this status applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='service_status', to='helpdesk.servicecategory')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Administrator who last updated this status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service status',
                'verbose_name_plural': 'Service statuses',
                'ordering': ('category__sort_order', 'category__name'),
            },
        ),
        migrations.CreateModel(
            name='TicketFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Very dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very satisfied')], help_text='Satisfaction rating from 1 (worst) to 5 (best).')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional free-text feedback from the requester.', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_feedback', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(help_text='The resolved/closed ticket this feedback is for.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='helpdesk.ticket')),
            ],
            options={
                'verbose_name': 'Ticket feedback',
                'verbose_name_plural': 'Ticket feedback',
                'ordering': ('-created_at',),
            },
        ),
    ]
