# Generated by Django 6.1.1 on 2026-10-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0030_service_status_and_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareresource',
            name='file',
            field=models.FileField(blank=True, help_text='Optional installer file hosted on the helpdesk server. Max 25 GB. When set, a download button appears on the public software page alongside (or instead of) the external download URL.', null=True, upload_to='software/%Y/%m/'),
        ),
    ]
