# Generated by Django 6.1.1 on 2026-10-06 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0031_software_file_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('total_size', models.BigIntegerField(help_text='Total file size in bytes')),
                ('total_chunks', models.PositiveIntegerField()),
                ('chunk_size', models.PositiveIntegerField(help_text='Expected bytes per chunk (last may be smaller)')),
                ('received_chunks', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('final_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chunked upload',
                'verbose_name_plural': 'Chunked uploads',
                'ordering': ('-created_at',),
            },
        ),
    ]
