# Generated by Django 6.1.1 on 2026-10-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0032_chunked_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='chunk_size_mb',
            field=models.PositiveSmallIntegerField(default=10, help_text='Size of each upload chunk in megabytes (1–95). Smaller values work better through Cloudflare Tunnel; larger values are more efficient on a direct server connection.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_upload_size_gb',
            field=models.PositiveSmallIntegerField(default=25, help_text='Maximum file upload size in gigabytes (1–100).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='upload_chunk_retries',
            field=models.PositiveSmallIntegerField(default=3, help_text='How many times to retry a failed chunk before aborting (0–10). Higher values help on unreliable connections.'),
        ),
    ]
