# Generated by Django 6.1.1 on 2026-10-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0033_site_settings_upload_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='chunk_size_mb',
            field=models.PositiveSmallIntegerField(default=2, help_text='Size of each upload chunk in megabytes (1–50). Values ≤ 5 MB are recommended behind Cloudflare Tunnel to avoid proxy read timeouts. Larger values improve throughput on a direct server connection.'),
        ),
    ]
