# Generated by Django 6.1.1 on 2026-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0034_chunk_size_default_2mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='event_type',
            field=models.CharField(choices=[('ticket_submitted', 'Ticket Submitted'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_reply', 'Staff Reply Sent'), ('status_changed', 'Status Changed'), ('waiting_requester', 'Ticket Waiting for Requester'), ('priority_changed', 'Priority Changed (by Requester)'), ('account_recovery', 'Account Recovery — Send Credentials'), ('recovery_unable_to_verify', 'Account Recovery — Unable to Verify')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('ticket_submitted', 'Ticket Submitted'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_reply', 'Staff Reply Sent'), ('status_changed', 'Status Changed'), ('waiting_requester', 'Ticket Waiting for Requester'), ('priority_changed', 'Priority Changed (by Requester)'), ('account_recovery', 'Account Recovery — Send Credentials'), ('recovery_unable_to_verify', 'Account Recovery — Unable to Verify')], max_length=30),
        ),
    ]
